name: Continuous integration
run-name: Continuous integration run by ${{ github.actor }}
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "doc/**"
      - "LICENSE"
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *" # Catch breakage from upstream Verus `main`

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Verus (latest main)
        uses: actions/checkout@v4
        with:
          repository: verus-lang/verus
          path: verus-src

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" \
            | sh -s -- --default-toolchain none -y
          . "$HOME/.cargo/env"
          rustup toolchain install

      - name: Build Verus
        run: |
          . "$HOME/.cargo/env"
          cd verus-src/source
          ./tools/get-z3.sh
          source ../tools/activate
          vargo build --release
          mv target-verus/release "$HOME/verus"

      - name: Verify temporal logic library
        run: |
          . "$HOME/.cargo/env"
          export PATH="$PATH:$HOME/verus"
          cargo verus verify --lib -- --rlimit 50 --time
