name: Continuous integration
run-name: Continuous integration run by ${{ github.actor }}
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "doc/**"
      - "LICENSE"
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  # should match vstd version in Cargo.toml
  # https://github.com/verus-lang/verus/releases
  VERUS_TAG: "0.2026.06.14.4ea7d0f"

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" \
            | sh -s -- --default-toolchain none -y
          . "$HOME/.cargo/env"
          rustup toolchain install

      - name: Download Verus
        run: |
          curl -fsSL -o /tmp/verus.zip \
            "https://github.com/verus-lang/verus/releases/download/release%2F${VERUS_TAG}/verus-${VERUS_TAG}-x86-linux.zip"
          unzip -q /tmp/verus.zip -d "$HOME"
          mv "$HOME/verus-x86-linux" "$HOME/verus"
          rm /tmp/verus.zip

      - name: Verify temporal logic library
        run: |
          . "$HOME/.cargo/env"
          export PATH="$PATH:$HOME/verus"
          cargo verus verify --lib -- --rlimit 50 --time
